### ISSUE TITLE
When is the update to 1.18.2? [Legendary Message]

### ISSUE THREAD

**Issue by ccyounga** [MoonflowerTeam/pollen#25]
### What version are you seeing the problem on?

1.18.x

### Describe the issue

```markdown
Months will pass, but we still will not see the light of day for version 1.18.2.. I open this topic to support my opinion. Maybe this will help the authors speed up the process.
```

### latest.log

```shell
-
```

**Comment by ccyounga** [comment]
Months will pass, but we still will not see the light of day for version 1.18.2.. I open this topic to support my opinion. Maybe this will help the authors speed up the process.

**Comment by Farcr** [comment]
Legendary message

For real though, we want 1.18.2 even more than you do, trust me.
