### ISSUE TITLE
[1.18.2 Performance] Spark reporting high MSPT from Pollen

### ISSUE THREAD

**Issue by itsdinkd** [MoonflowerTeam/pollen#40]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
Run Spark profiler in server with people
See results
```

### latest.log

```shell
https://spark.lucko.me/p4J2fXnR6v?hl=16483,20079,26303,32576,34625,36688,38414,40907,42761,44224,45189,46209,46683,47565,48464,49110,49859,50644,51381,52756,53219,53582,54597,54998,55475,55766,56007,56273,56638,56989,57420,57662,57742,57864,57971,76435,6047
```

**Comment by Ocelot5836** [comment]
According to the profiling you gave Pollen events are taking a tiny fraction of a tick, even after considering all events. It takes up a reasonable amount of time per tick only if listeners are registered to events.

**Comment by itsdinkd** [comment]
> According to the profiling you gave Pollen events are taking a tiny fraction of a tick, even after considering all events. It takes up a reasonable amount of time per tick only if listeners are registered to events.

??? It took 3944 ms which is 78 ticks.

**Comment by Ocelot5836** [comment]
Spark reports the total time is 438027ms, which is 21901 ticks total. That means 3944ms is literally 0.9% of the tick time. It takes more time to tick animal movement (5033ms) than invoke events.

**Comment by itsdinkd** [comment]
I see what you mean now. Thanks for clarifying

**Comment by Ocelot5836** [comment]
np
