### ISSUE TITLE
Issue with Animations

### ISSUE THREAD

**Issue by itsdinkd** [MoonflowerTeam/pollen#8]
### What version are you seeing the problem on?

1.18.x

### Describe the issue

```markdown
Looks like there is an issue with any entity that uses GeckoLib and Pollen. This is all in my logs upon launching the game


Failed Errors: https://gist.github.com/itsdinkd/4156c073acead184b7263bc7646694f5
```

### latest.log

```shell
Log: https://gist.github.com/itsdinkd/4156c073acead184b7263bc7646694f5
```

**Comment by jacksonhardaway** [comment]
This isn't an issue, but rather just due to GeckoLib and Pollen using the same folders. Will be changed in the future.

**Comment by itsdinkd** [comment]
Once updated I'll throw it back into my modpack. Dont want to create extra
logging for users concerned about write usage on SSDs.

 Nice work on the mannequin can't wait for my players to use it :)

**Comment by jacksonhardaway** [comment]
I wouldn't be concerned about space, it only logs when resources are loading (startup and F3 + T)

**Comment by itsdinkd** [comment]
Not so much about space, but more so extra writes from an SSD drive. I’ve had a bunch of complaints from players with NVME drives that unnecessary warnings/errors getting logged is killing their NVME SSD Drive due to all the writes. Normally, I wouldn’t care. People a crazy, lol.    From: jacksonSent: Tuesday, February 22, 2022 10:12 PMTo: MoonflowerTeam/pollenCc: itsdinkd; AuthorSubject: Re: [MoonflowerTeam/pollen] Issue with Animations (Issue #8) I wouldn't be concerned about space, it only logs when resources are loading (startup and F3 + T)—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Sunconure11** [comment]
Did this get resolved?

**Comment by itsdinkd** [comment]
Checking today, though i dont see a commit attached to this issue, so maybe not?
