### ISSUE TITLE
Error Loading Pollen-2.1.0 on Minecraft 1.19.2 Forge 43.2.21

### ISSUE THREAD

**Issue by FanUCK** [MoonflowerTeam/pollen#81]
### What version are you seeing the problem on?

1.19.2

### Describe the issue

Game crashed when I installed it for the first time.
The problem only happens when I enabled Pollen

### latest.log

```shell
https://pastebin.com/NvU1Swct
```

**Comment by Ocelot5836** [comment]
Did you add architectury api?
