### ISSUE TITLE
This version of the mod has a rendering incompatibility with the following mod below.

### ISSUE THREAD

**Issue by lSherozl** [MoonflowerTeam/pollen#82]
### What version are you seeing the problem on?

1.19.2

### Describe the issue

https://github.com/TartaricAcid/TouhouLittleMaid/issues

https://github.com/TartaricAcid/TouhouLittleMaid/issues/420

https://github.com/TartaricAcid/TouhouLittleMaid/issues/421

### latest.log

```shell
Logs provided in links
```

**Comment by TartaricAcid** [comment]
fix in: https://github.com/TartaricAcid/TouhouLittleMaid/commit/2619fed2f2d9f403fcfa26ad480221686dac6305

**Comment by lSherozl** [comment]
Yup Fixed by Owner of Mod
