### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by Shiumee** [MoonflowerTeam/pollen#83]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

1. Add in etched 2.2.1 and pollen 1.6.1 into modpack
2. crash on bootup

### latest.log

```shell
https://pastebin.com/SXzHmPn0
```

**Comment by jacksonhardaway** [comment]
1.18 is no longer supported for Etched and Pollen has been discontinued.
